package control

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"harness.local/engorch/internal/canonical"
	"harness.local/engorch/internal/controllerstate"
	"harness.local/engorch/internal/engineeringplan"
	"harness.local/engorch/internal/journal"
	"harness.local/engorch/internal/repository"
	"harness.local/engorch/internal/runtime"
)

// This file owns ONLY the genuine observed-signal integration gap left by
// TestStagedObservedPreparationReplayRoundTrip: that test has no admitted RI
// (advisory fallback only) and its substitution check compares bytes without
// submitting the mutation to the replay validator. The tests below use an
// exact source-bound admitted PlannerGoContext (real Git commit/tree via
// repository.Discover, real RI admission via AdmitPlannerGoContext through the
// existing Append/Replay seam) with staged selector 3, and every substitution
// is passed through Replay or the replay validator.
//
// Helpers use the soi prefix to avoid collisions. This file deliberately does
// not call observedFixtureIdentity (its signature may become t-aware).

func soiRequireRIBinary(t *testing.T) (string, string) {
	t.Helper()
	exe := os.Getenv("ENGORCH_RI_BINARY")
	if exe == "" {
		t.Skip("NOTRUN: missing ENGORCH_RI_BINARY binding for genuine RI admission; cannot build source-bound PlannerGoContext without the pinned offline parser")
	}
	cleaned := filepath.Clean(exe)
	bin, err := os.ReadFile(cleaned)
	if err != nil {
		t.Fatalf("RI binary unreadable: %v", err)
	}
	sum := sha256.Sum256(bin)
	return cleaned, hex.EncodeToString(sum[:])
}

func soiC2Files() map[string]string {
	return map[string]string{
		"pkg/a.go":   "package pkg\nfunc A() {}\n",
		"pkg/b.go":   "package pkg\nfunc B() {}\n",
		"other/c.go": "package other\nfunc C() {}\n",
	}
}

func soiImplTask(id, write string) engineeringplan.Task {
	return engineeringplan.Task{ID: id, Kind: engineeringplan.Implementation, Title: "Implement " + id, ScopePaths: []string{"."}, WritePaths: []string{write}, ExpectedEvidence: []engineeringplan.Evidence{{Kind: "file", Description: "output exists"}}, EstimatedSeconds: 30}
}

func soiVerifyReviewTasks(deps ...string) []engineeringplan.Task {
	return []engineeringplan.Task{
		{ID: "verify", Kind: engineeringplan.Verification, Title: "Run native checks", Dependencies: deps, ScopePaths: []string{"."}, ExpectedEvidence: []engineeringplan.Evidence{{Kind: "check", Description: "checks pass"}}, EstimatedSeconds: 30},
		{ID: "review", Kind: engineeringplan.Review, Title: "Review candidate", Dependencies: []string{"verify"}, ScopePaths: []string{"."}, ExpectedEvidence: []engineeringplan.Evidence{{Kind: "review", Description: "approve"}}, EstimatedSeconds: 30},
	}
}

func soiC2Graph() engineeringplan.Graph {
	tasks := []engineeringplan.Task{
		soiImplTask("impl-a", "pkg/a.go"),
		soiImplTask("impl-b", "pkg/b.go"),
		soiImplTask("impl-c", "other/c.go"),
	}
	tasks = append(tasks, soiVerifyReviewTasks("impl-a", "impl-b", "impl-c")...)
	return engineeringplan.Graph{Version: engineeringplan.Version, Mode: engineeringplan.ModeGraph, Summary: "observed C2 integration", Tasks: tasks}
}

func soiC4Files() map[string]string {
	return map[string]string{
		"bool.go":     "// Code generated by gen-wrapper. DO NOT EDIT.\npackage sample\ntype Bool struct{}\n",
		"bool_ext.go": "package sample\n//go:generate bin/gen-wrapper -name=Bool -file=bool.go\nfunc (b *Bool) Toggle() {}\n",
	}
}

func soiC4Graph() engineeringplan.Graph {
	tasks := []engineeringplan.Task{
		soiImplTask("impl-gen", "bool_ext.go"),
		soiImplTask("impl-out", "bool.go"),
	}
	tasks = append(tasks, soiVerifyReviewTasks("impl-gen", "impl-out")...)
	return engineeringplan.Graph{Version: engineeringplan.Version, Mode: engineeringplan.ModeGraph, Summary: "observed C4 integration", Tasks: tasks}
}

// soiWriteCorpus validates Go syntax and writes the admitted corpus. It is
// shared by the C2/C4 integrations so the file-write sequence cannot diverge.
func soiWriteCorpus(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for name, content := range files {
		if filepath.Ext(name) == ".go" {
			if _, err := parser.ParseFile(token.NewFileSet(), name, content, parser.AllErrors); err != nil {
				t.Fatalf("invalid Go fixture %q: %v", name, err)
			}
		}
		full := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(full), 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0600); err != nil {
			t.Fatal(err)
		}
	}
}

// soiCommitCorpus commits the written corpus with the fixture identity.
func soiCommitCorpus(t *testing.T, root, message string) {
	t.Helper()
	for _, args := range [][]string{{"add", "."}, {"-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", "commit", "-qm", message}} {
		if out, err := autonomousGitCmd(t, root, args); err != nil {
			t.Fatalf("fixture commit failed: %v %s", err, string(out))
		}
	}
}

// soiStagedWithAdmittedRI builds a real Git corpus, discovers its real
// commit/tree identity, creates a staged run bound to that source, and admits
// the PlannerGoContext through the real AdmitPlannerGoContext seam (which
// validates and Appends via Replay). It then drives the run through
// plan.recorded, authorization, graph recording and workspace start, returning
// the journal path, the pre-preparation snapshot, the genuinely admitted
// record and the creation. No provider is invoked.
func soiStagedWithAdmittedRI(t *testing.T, selector int, plannerMode, objective string, files map[string]string, graph engineeringplan.Graph) (string, Snapshot, PlannerGoContextRecord, Creation) {
	t.Helper()
	executable, execHash := soiRequireRIBinary(t)
	c := stagedThreeTaskCreation(t)
	c.Execution.IsolationCohortSelectorVersion = selector
	c.Config.PlannerContract = plannerContractGraphV9
	c.Execution.PlannerContext = plannerMode
	c.Execution.PlannerContextRIExecutable = executable
	c.Execution.PlannerContextRIExecutableSHA256 = execHash
	c.Objective = objective
	if err := c.Execution.Validate(); err != nil {
		t.Fatalf("staged RI creation rejected: %v", err)
	}
	if err := c.Config.Validate(); err != nil {
		t.Fatalf("staged RI config rejected: %v", err)
	}
	root := c.Repository.Root
	autonomousGitInit(t, root)
	soiWriteCorpus(t, root, files)
	soiCommitCorpus(t, root, "observed integration fixture")
	repo, err := repository.Discover(context.Background(), root, c.Config.Repository)
	if err != nil {
		t.Fatal(err)
	}
	c.Repository = repo
	paths, err := controllerstate.Resolve(c.Config.ControllerStateRoot, c.Repository)
	if err != nil {
		t.Fatal(err)
	}
	if err := controllerstate.Initialize(paths, c.Repository); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(paths.Runs, 0700); err != nil {
		t.Fatal(err)
	}
	runID, err := canonical.Hash("harness.run.v1", c)
	if err != nil {
		t.Fatal(err)
	}
	path, err := paths.Run(runID)
	if err != nil {
		t.Fatal(err)
	}
	if err := Append(path, "run.created", c); err != nil {
		t.Fatal(err)
	}
	record, err := AdmitPlannerGoContext(context.Background(), path)
	if err != nil {
		t.Fatalf("genuine RI admission failed: %v", err)
	}
	if err := Append(path, "planning.started", struct{}{}); err != nil {
		t.Fatal(err)
	}
	planningSnapshot, err := Inspect(path)
	if err != nil {
		t.Fatal(err)
	}
	invocation, err := plannerInvocationForSnapshot(planningSnapshot)
	if err != nil {
		t.Fatal(err)
	}
	model := invocation.Profile.Model
	raw, err := json.Marshal(graph)
	if err != nil {
		t.Fatal(err)
	}
	if err := Append(path, "plan.recorded", runtime.Result{Version: 1, InvocationID: invocation.ID, Requested: invocation.Profile, ObservedModel: &model, Output: string(raw)}); err != nil {
		t.Fatal(err)
	}
	s, err := Inspect(path)
	if err != nil {
		t.Fatal(err)
	}
	if accepted, err := parseAcceptedGraph(s); err != nil || accepted.Summary != graph.Summary {
		t.Fatalf("staged graph fixture rejected: %v", err)
	}
	machineAuthorizePlan(t, path, s)
	if _, err := ensureGraphRecorded(path, s); err != nil {
		t.Fatal(err)
	}
	if _, err := StartWorkspace(context.Background(), path); err != nil {
		t.Fatal(err)
	}
	current, err := Inspect(path)
	if err != nil {
		t.Fatal(err)
	}
	return path, current, record, c
}

func soiReadyImplementations(t *testing.T, s Snapshot) []engineeringplan.Task {
	t.Helper()
	ready, err := graphReadyTasks(s)
	if err != nil {
		t.Fatal(err)
	}
	var impls []engineeringplan.Task
	for _, task := range ready {
		if task.Kind == engineeringplan.Implementation {
			impls = append(impls, task)
		}
	}
	return impls
}

func soiWaveIDSet(waves [][]string) []map[string]bool {
	out := make([]map[string]bool, len(waves))
	for i, wave := range waves {
		set := map[string]bool{}
		for _, id := range wave {
			set[id] = true
		}
		out[i] = set
	}
	return out
}

func soiSameWaves(a, b [][]string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if len(a[i]) != len(b[i]) {
			return false
		}
		for j := range a[i] {
			if a[i][j] != b[i][j] {
				return false
			}
		}
	}
	return true
}

func soiForgedEventsWithPayload(t *testing.T, events []journal.Event, kind string, payload []byte) []journal.Event {
	t.Helper()
	out := append([]journal.Event(nil), events...)
	replaced := false
	for i, e := range out {
		if e.Kind == kind {
			out[i].Payload = append([]byte(nil), payload...)
			replaced = true
			break
		}
	}
	if !replaced {
		t.Fatalf("no %q event to substitute", kind)
	}
	return out
}

// TestStagedObservedIntegrationC2WavesDifferAndReplayRoundTrip is the genuine
// observed-signal integration missing from
// TestStagedObservedPreparationReplayRoundTrip: exact source-bound admitted
// RI, disjoint current ready tasks (two same-package Go files plus a third
// other-package file, maxParallel 2), controller selector-3 waves that differ
// from selector 2 under the same estimates/source, exact preparation replay
// through full Replay with the same admitted record, and source/evidence/
// preparation substitutions rejected through Replay (never mere byte
// comparison). No live pipeline or performance claim; no providers.
func TestStagedObservedIntegrationC2WavesDifferAndReplayRoundTrip(t *testing.T) {
	path, s, record, _ := soiStagedWithAdmittedRI(t, 3, plannerContextGoSourceV1, "Update observed package owners and keep disjoint writes", soiC2Files(), soiC2Graph())
	if record.Unavailable != "" {
		t.Skipf("NOTRUN: genuine RI admission reports unavailable corpus %q; missing eligible complete Go source binding", record.Unavailable)
	}
	if record.Version != plannerGoContextVersion || record.Graph == nil {
		t.Skipf("NOTRUN: genuine RI admission did not bind v1 graph evidence; missing graph/source binding version=%d haveGraph=%v", record.Version, record.Graph != nil)
	}
	// Inspect already replayed planner.go-context-admitted through the real
	// Replay seam; the admitted identity must be present before it is trusted.
	if s.PlannerGoContext == nil || s.PlannerGoContext.RecordID != record.RecordID {
		t.Fatalf("admitted RI did not replay through Inspect: %+v", s.PlannerGoContext)
	}
	impls := soiReadyImplementations(t, s)
	if len(impls) != 3 {
		t.Fatalf("expected three current ready implementations, got %d", len(impls))
	}
	byWrite := map[string]string{}
	for _, task := range impls {
		if len(task.WritePaths) != 1 {
			t.Fatalf("fixture task %q must own exactly one write path", task.ID)
		}
		byWrite[task.WritePaths[0]] = task.ID
	}
	if byWrite["pkg/a.go"] == "" || byWrite["pkg/b.go"] == "" || byWrite["other/c.go"] == "" {
		t.Fatalf("ready tasks are not disjoint over the admitted corpus: %+v", byWrite)
	}
	observed, haveRI, err := deriveObservedCouplings(s, impls)
	if err != nil || !haveRI {
		t.Fatalf("NOTRUN: genuine admission yielded no observed set; missing same-package binding err=%v haveRI=%v", err, haveRI)
	}
	if len(observed) != 1 || observed[0].Level != engineeringplan.CouplingC2 || observed[0].Provenance != engineeringplan.CouplingProvenanceTopologyObserved {
		t.Skipf("NOTRUN: genuine admission did not yield the expected C2 same-package pair; missing source-topology binding got %+v", observed)
	}
	// Controller selector-3 waves must differ from selector 2 under the same
	// estimates/source: selector 2 co-schedules the same-package pair while
	// observed C2 forces an unrelated (cross-package) pair.
	prep3, err := expectedStagedPreparation(s)
	if err != nil {
		t.Fatalf("selector 3 expected preparation failed: %v", err)
	}
	if prep3.CohortSelectorVersion != 3 {
		t.Fatalf("expected selector 3, got %d", prep3.CohortSelectorVersion)
	}
	s2 := s
	execCopy := *s.Creation.Execution
	execCopy.IsolationCohortSelectorVersion = 2
	s2.Creation.Execution = &execCopy
	prep2, err := expectedStagedPreparation(s2)
	if err != nil {
		t.Fatalf("selector 2 expected preparation failed: %v", err)
	}
	if soiSameWaves(prep3.Waves, prep2.Waves) {
		t.Fatalf("selector 3 waves did not differ from selector 2 under same estimates/source: %+v", prep3.Waves)
	}
	if len(prep3.Waves) != 2 || len(prep3.Waves[0]) != 2 {
		t.Fatalf("expected two waves with a two-task first wave, got %+v", prep3.Waves)
	}
	first := soiWaveIDSet(prep3.Waves)[0]
	if first[byWrite["pkg/a.go"]] && first[byWrite["pkg/b.go"]] {
		t.Fatalf("observed C2 pair co-scheduled in selector 3 first wave: %+v", prep3.Waves)
	}
	if !first[byWrite["other/c.go"]] {
		t.Fatalf("observed C2 did not choose the unrelated pair in selector 3 first wave: %+v", prep3.Waves)
	}
	secondFirst := soiWaveIDSet(prep2.Waves)[0]
	if !(secondFirst[byWrite["pkg/a.go"]] && secondFirst[byWrite["pkg/b.go"]]) {
		t.Fatalf("selector 2 did not co-schedule the same-package pair without observed signal: %+v", prep2.Waves)
	}
	// Exact staged preparation must replay through full Replay with the same
	// admitted RI record. Pure Snapshot comparison alone is not called full
	// run acceptance here: PrepareStagedCohort appends via the Replay seam and
	// journal.Read+Replay revalidates the whole run.
	admitted, err := PrepareStagedCohort(context.Background(), path)
	if err != nil {
		t.Fatalf("staged preparation append failed: %v", err)
	}
	if !sameCanonical(prep3, admitted) {
		t.Fatal("controller prepared waves differ from expected preparation")
	}
	events, err := journal.Read(path)
	if err != nil {
		t.Fatal(err)
	}
	replayed, err := Replay(events)
	if err != nil {
		t.Fatalf("full Replay rejected the exact run: %v", err)
	}
	if replayed.GraphIsolationPreparation == nil || !sameCanonical(*replayed.GraphIsolationPreparation, prep3) {
		t.Fatal("exact staged preparation did not replay through full Replay")
	}
	if replayed.PlannerGoContext == nil || replayed.PlannerGoContext.RecordID != record.RecordID {
		t.Fatal("same admitted RI record did not survive full Replay")
	}
	// Substituted source must be rejected through full Replay, not byte
	// comparison. Self-rehash so the failure proves source binding, not ID
	// shape.
	forgedSource := record
	forgedSources := append([]repository.SourceDigest(nil), forgedSource.Sources...)
	forgedSources[0].SHA256 = strings.Repeat("e", 64)
	forgedSource.Sources = forgedSources
	var forgeErr error
	forgedSource.RecordID, forgeErr = plannerGoContextRecordID(forgedSource)
	if forgeErr != nil {
		t.Fatal(forgeErr)
	}
	forgedSourceBytes, err := canonical.Bytes(forgedSource)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Replay(soiForgedEventsWithPayload(t, events, "planner.go-context-admitted", forgedSourceBytes)); err == nil {
		t.Fatal("full Replay admitted substituted source evidence")
	}
	// Substituted graph evidence must be rejected through the replay
	// validator. Forge one fact SHA away from the admitted digest and
	// self-rehash.
	mutatedGraph := *record.Graph
	if len(mutatedGraph.Files) == 0 {
		t.Fatal("admitted graph has no files to substitute")
	}
	graphCopy := mutatedGraph
	graphCopy.Files = append(graphCopy.Files[:0:0], mutatedGraph.Files...)
	graphCopy.Files[0].Facts.SourceSHA256 = strings.Repeat("f", 64)
	mutated := record
	mutated.Graph = &graphCopy
	mutated.RecordID, err = plannerGoContextRecordID(mutated)
	if err != nil {
		t.Fatal(err)
	}
	mutatedBytes, err := canonical.Bytes(mutated)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Replay(soiForgedEventsWithPayload(t, events, "planner.go-context-admitted", mutatedBytes)); err == nil {
		t.Fatal("replay validator admitted substituted graph evidence")
	}
	// Substituted preparation must be rejected through full Replay.
	forgedPrep := prep3
	forgedWaves := append([][]string(nil), forgedPrep.Waves...)
	if len(forgedWaves[0]) == 2 {
		forgedWaves[0] = forgedWaves[0][:1]
	} else {
		forgedWaves[0] = append(forgedWaves[0], "impl-a")
	}
	forgedPrep.Waves = forgedWaves
	forgedPrep.PreparationID = ""
	forgedPrep.PreparationID, err = canonical.Hash("harness.graph-staged-preparation.v1", forgedPrep)
	if err != nil {
		t.Fatal(err)
	}
	forgedPrepBytes, err := canonical.Bytes(forgedPrep)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Replay(soiForgedEventsWithPayload(t, events, "graph.staged-prepared", forgedPrepBytes)); err == nil {
		t.Fatal("full Replay admitted substituted staged preparation")
	}
}

// TestStagedObservedIntegrationC4UnsafeRejectedPreEffect proves the C4 unsafe
// generator-family gate fires before any child/fork intent when the same
// source-bound admission carries an explicit generation family. No fork,
// file intent or preparation may exist after rejection. If the fixture cannot
// bind generation evidence, the test stays NOTRUN rather than fabricating.
func TestStagedObservedIntegrationC4UnsafeRejectedPreEffect(t *testing.T) {
	path, s, record, _ := soiStagedWithAdmittedRI(t, 3, plannerContextGoSourceV2, "Update generated Bool behavior through its generator template", soiC4Files(), soiC4Graph())
	if record.Unavailable != "" {
		t.Skipf("NOTRUN: genuine RI admission reports unavailable corpus %q; missing generation source binding", record.Unavailable)
	}
	if record.GenerationMetadata == nil || record.Graph == nil {
		t.Skipf("NOTRUN: genuine admission did not bind generation metadata; missing generator proof version=%d", record.Version)
	}
	impls := soiReadyImplementations(t, s)
	if len(impls) != 2 {
		t.Fatalf("expected two current ready generator-family implementations, got %d", len(impls))
	}
	observed, haveRI, err := deriveObservedCouplings(s, impls)
	if err != nil || !haveRI {
		t.Fatalf("NOTRUN: genuine admission yielded no observed set; missing generator binding err=%v haveRI=%v", err, haveRI)
	}
	foundC4 := false
	for _, c := range observed {
		if c.Level == engineeringplan.CouplingC4 && c.Provenance == engineeringplan.CouplingProvenanceGeneratorObserved {
			foundC4 = true
		}
		if c.Level == engineeringplan.CouplingC3 {
			t.Fatalf("same-generation evidence became C3: %+v", c)
		}
	}
	if !foundC4 {
		t.Skipf("NOTRUN: genuine admission did not yield C4 generator family; missing generation edge got %+v", observed)
	}
	demands, err := isolationResourceDemands(s, impls)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := engineeringplan.SelectResourceWavesWithObservedCouplings(s.Graph.Graph, impls, demands, *s.Creation.Execution.IsolationCapacity, s.Creation.Execution.EffectiveMaxParallel(), s.Graph.Graph.Couplings, observed); err == nil {
		t.Fatal("observed C4 split admitted without one owner or dependency")
	}
	// The controller preparation itself must fail before any child/fork
	// intent is admitted.
	if _, err := expectedStagedPreparation(s); err == nil {
		t.Fatal("staged preparation admitted an unsafe C4 generator split")
	} else if !strings.Contains(err.Error(), "C4") && !strings.Contains(err.Error(), "coupling") && !strings.Contains(err.Error(), "generator") && !strings.Contains(err.Error(), "split") {
		t.Fatalf("C4 rejection did not name the coupling gate: %v", err)
	}
	current, err := Inspect(path)
	if err != nil {
		t.Fatal(err)
	}
	if current.GraphIsolationPreparation != nil || current.FileIntent != nil || len(current.GraphStagedForks) != 0 {
		t.Fatal("unsafe C4 run admitted a pre-effect before rejection")
	}
}
