package ri

import (
	"reflect"
	"strings"
	"testing"
)

func topologyFixture(t *testing.T) GoEngineeringGraph {
	t.Helper()
	producer := strings.Repeat("b", 64)
	ownerSource := "package gen\n//go:generate go run .\n"
	owner := graphInput("gen/main.go", ownerSource, GoPackageBinding{ImportPath: "example.com/m/gen", ModulePath: "example.com/m"}, nil, nil, nil, []string{"//go:generate go run ."}, producer)
	outputSource := "// Code generated by gen. DO NOT EDIT.\npackage api\n"
	a := graphInput("api/a.go", outputSource, GoPackageBinding{ImportPath: "example.com/m/api", ModulePath: "example.com/m"}, nil, nil, nil, []string{"// Code generated by gen. DO NOT EDIT."}, producer)
	b := graphInput("api/b.go", outputSource, a.Package, nil, nil, nil, a.Facts.GeneratedMarkers, producer)
	testSource := "package api_test\n"
	tests := graphInput("api/a_test.go", testSource, GoPackageBinding{ImportPath: "example.com/m/api_test", ModulePath: "example.com/m", TestOfImportPath: "example.com/m/api"}, nil, nil, nil, nil, producer)
	consumerSource := "package consumer\nimport \"example.com/m/api\"\n"
	imports := []GoImport{{Path: "example.com/m/api", Range: graphSpan(consumerSource, `"example.com/m/api"`, 0)}}
	c := graphInput("consumer/a.go", consumerSource, GoPackageBinding{ImportPath: "example.com/m/consumer", ModulePath: "example.com/m"}, nil, imports, nil, nil, producer)
	d := graphInput("consumer/b.go", consumerSource, c.Package, nil, imports, nil, nil, producer)
	e := graphInput("other/a.go", consumerSource, GoPackageBinding{ImportPath: "example.com/m/other", ModulePath: "example.com/m"}, nil, imports, nil, nil, producer)
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{owner, a, b, tests, c, d, e}, Generators: []GoGeneratorBinding{{GeneratorPath: owner.Facts.Path, GeneratedPath: a.Facts.Path, Directive: "//go:generate go run ."}, {GeneratorPath: owner.Facts.Path, GeneratedPath: b.Facts.Path, Directive: "//go:generate go run ."}}})
	if err != nil {
		t.Fatal(err)
	}
	return graph
}

func TestGoTopologyGeneratorClosureReviewSplitAndHubDegree(t *testing.T) {
	graph := topologyFixture(t)
	before := graph.Digest
	out, err := QueryGoTopology(graph, []string{"api/a.go"}, 2)
	if err != nil {
		t.Fatal(err)
	}
	if out.GraphDigest != graph.Digest || out.Coverage != "PARTIAL" || out.Digest == "" || graph.Digest != before {
		t.Fatal("topology lost immutable graph identity")
	}
	foundOwner, foundSibling, foundTest, foundHub := false, false, false, false
	for _, g := range out.ReviewGroups {
		for _, p := range g.Paths {
			foundOwner = foundOwner || p == "gen/main.go"
			foundSibling = foundSibling || p == "api/b.go"
			foundTest = foundTest || p == "api/a_test.go"
		}
		if len(g.Paths) > 2 {
			t.Fatal("unbounded group")
		}
	}
	for _, m := range out.Modules {
		if m.Label == "example.com/m/api" {
			foundHub = m.SharedHub && m.ObservedImporters == 2
		}
	}
	if !foundOwner || !foundSibling || !foundTest || !foundHub {
		t.Fatalf("missing owner/sibling/test/hub: %v %v %v %v", foundOwner, foundSibling, foundTest, foundHub)
	}
	var component string
	for _, g := range out.ReviewGroups {
		for _, p := range g.Paths {
			if p == "gen/main.go" || p == "api/a.go" || p == "api/b.go" || p == "api/a_test.go" {
				if component == "" {
					component = g.ComponentID
				}
				if component != g.ComponentID || !g.Split {
					t.Fatal("split detached coupled files")
				}
			}
		}
	}
	again, err := QueryGoTopology(graph, []string{"api/a.go"}, 2)
	if err != nil || !reflect.DeepEqual(out, again) {
		t.Fatal("nondeterministic topology")
	}
}

func TestGoTopologyRejectsInvalidQueriesAndGraph(t *testing.T) {
	graph := topologyFixture(t)
	for _, paths := range [][]string{nil, {"absent.go"}, {"api/a.go", "api/a.go"}, {"../api/a.go"}} {
		if _, err := QueryGoTopology(graph, paths, 2); err == nil {
			t.Fatal("accepted invalid changed paths")
		}
	}
	for _, limit := range []int{0, 33} {
		if _, err := QueryGoTopology(graph, []string{"api/a.go"}, limit); err == nil {
			t.Fatal("accepted invalid group limit")
		}
	}
	graph.Digest = strings.Repeat("f", 64)
	if _, err := QueryGoTopology(graph, []string{"api/a.go"}, 2); err == nil {
		t.Fatal("accepted graph substitution")
	}
}

func TestGoTopologySourceLocalImportsDoNotBecomeResolvedDependencies(t *testing.T) {
	producer := strings.Repeat("b", 64)
	sourceID := strings.Repeat("0", 64)
	apiSource := "package api\n"
	apiBinding, err := SourceLocalGoPackageBinding(sourceID, "api/a.go", "api")
	if err != nil {
		t.Fatal(err)
	}
	consumerSource := "package consumer\nimport \"example.com/m/api\"\n"
	consumerBinding, err := SourceLocalGoPackageBinding(sourceID, "consumer/a.go", "consumer")
	if err != nil {
		t.Fatal(err)
	}
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, ProducerSHA256: producer, Files: []GoGraphFileInput{graphInput("api/a.go", apiSource, apiBinding, nil, nil, nil, nil, producer), graphInput("consumer/a.go", consumerSource, consumerBinding, nil, []GoImport{{Path: "example.com/m/api", Range: graphSpan(consumerSource, `"example.com/m/api"`, 0)}}, nil, nil, producer)}})
	if err != nil {
		t.Fatal(err)
	}
	out, err := QueryGoTopology(graph, []string{"api/a.go"}, 2)
	if err != nil {
		t.Fatal(err)
	}
	for _, m := range out.Modules {
		if m.ObservedImporters != 0 || m.ObservedDependencies != 0 || m.SharedHub {
			t.Fatal("source-local package inferred import ownership")
		}
	}
}
