package ri

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"harness.local/engorch/internal/canonical"
	"harness.local/engorch/internal/repository"
)

func graphInput(path, source string, pkg GoPackageBinding, declarations []GoSymbol, imports []GoImport, calls []GoCall, markers []string, producer string) GoGraphFileInput {
	content := []byte(source)
	sourceSum := sha256.Sum256(content)
	facts := GoFileFacts{
		Schema: goFactsSchema, Language: "go", ParserVersion: goFactsParserVersion,
		Path: path, SourceSHA256: hex.EncodeToString(sourceSum[:]), ProducerSHA256: producer,
		SyntaxErrors: false, Coverage: "PARTIAL", Declarations: declarations,
		Imports: imports, Calls: calls, GeneratedMarkers: markers, Cache: "miss", ParseCount: 1,
	}
	var err error
	facts.CacheKey, err = canonical.Hash("harness.ri.go-file-facts.v1", map[string]any{
		"schema": goFactsSchema, "language": "go", "parser": goFactsParserVersion,
		"path": path, "source_sha256": facts.SourceSHA256, "producer_sha256": producer,
	})
	if err != nil {
		panic(err)
	}
	body := facts
	body.BodySHA256 = ""
	body.Cache = ""
	body.ParseCount = 0
	bodyBytes, err := canonical.Bytes(body)
	if err != nil {
		panic(err)
	}
	bodySum := sha256.Sum256(bodyBytes)
	facts.BodySHA256 = hex.EncodeToString(bodySum[:])
	return GoGraphFileInput{Facts: facts, Source: content, Package: pkg}
}

func graphSpan(source, text string, from int) GoRange {
	start := strings.Index(source[from:], text)
	if start < 0 {
		panic("fixture text not found: " + text)
	}
	start += from
	return GoRange{StartByte: start, EndByte: start + len(text)}
}

func TestBuildGoEngineeringGraphDeterministicRelationsAndQueries(t *testing.T) {
	producer := strings.Repeat("b", 64)
	appSource := "package api\nimport \"fmt\"\n//go:generate go run ./cmd/gen\nfunc New() { fmt.Println(\"x\"); helper() }\nfunc helper() {}\n"
	app := graphInput("src/api.go", appSource, GoPackageBinding{ImportPath: "example.com/m/api", ModulePath: "example.com/m"},
		[]GoSymbol{
			{Name: "New", Kind: "function_declaration", Range: graphSpan(appSource, "New", 0)},
			{Name: "helper", Kind: "function_declaration", Range: graphSpan(appSource, "helper", 0)},
		},
		[]GoImport{{Path: "fmt", Range: graphSpan(appSource, `"fmt"`, 0)}},
		[]GoCall{{Spelling: "fmt.Println", Resolution: "UNRESOLVED", Range: graphSpan(appSource, "fmt.Println", 0)}, {Spelling: "helper", Resolution: "UNRESOLVED", Range: graphSpan(appSource, "helper", strings.Index(appSource, "fmt.Println"))}},
		[]string{"//go:generate go run ./cmd/gen"}, producer)
	generatedSource := "// Code generated by command. DO NOT EDIT.\npackage api\n"
	generated := graphInput("src/generated.go", generatedSource, GoPackageBinding{ImportPath: "example.com/m/api", ModulePath: "example.com/m"}, nil, nil, nil, []string{"// Code generated by command. DO NOT EDIT."}, producer)
	testSource := "package api\nfunc TestNew() { New() }\n"
	testFile := graphInput("src/api_test.go", testSource, GoPackageBinding{ImportPath: "example.com/m/api_test", ModulePath: "example.com/m", TestOfImportPath: "example.com/m/api"},
		[]GoSymbol{{Name: "TestNew", Kind: "function_declaration", Test: true, Range: graphSpan(testSource, "TestNew", 0)}}, nil,
		[]GoCall{{Spelling: "New", Resolution: "UNRESOLVED", Range: graphSpan(testSource, "New", strings.Index(testSource, "() {")+4)}}, nil, producer)
	consumerSource := "package consumer\nimport api \"example.com/m/api\"\nimport \"fmt\"\nfunc Use() { api.New(); fmt.Println() }\n"
	consumer := graphInput("consumer/use.go", consumerSource, GoPackageBinding{ImportPath: "example.com/m/consumer", ModulePath: "example.com/m"},
		[]GoSymbol{{Name: "Use", Kind: "function_declaration", Range: graphSpan(consumerSource, "Use", 0)}},
		[]GoImport{{Path: "example.com/m/api", Alias: ptrString("api"), Range: graphSpan(consumerSource, `api "example.com/m/api"`, 0)}, {Path: "fmt", Range: graphSpan(consumerSource, `"fmt"`, 0)}},
		[]GoCall{{Spelling: "api.New", Resolution: "UNRESOLVED", Range: graphSpan(consumerSource, "api.New", 0)}, {Spelling: "fmt.Println", Resolution: "UNRESOLVED", Range: graphSpan(consumerSource, "fmt.Println", 0)}}, nil, producer)
	internalTestSource := "package api\nfunc TestInternal() {}\n"
	internalTest := graphInput("src/api_internal_test.go", internalTestSource, GoPackageBinding{ImportPath: "example.com/m/api", ModulePath: "example.com/m"},
		[]GoSymbol{{Name: "TestInternal", Kind: "function_declaration", Test: true, Range: graphSpan(internalTestSource, "TestInternal", 0)}}, nil, nil, nil, producer)
	input := GoGraphSnapshotInput{
		SourceID: strings.Repeat("0", 64), CandidateID: strings.Repeat("a", 64), ProducerSHA256: producer,
		Files:      []GoGraphFileInput{app, generated, testFile, consumer, internalTest},
		Generators: []GoGeneratorBinding{{GeneratorPath: "src/api.go", GeneratedPath: "src/generated.go", Directive: "//go:generate go run ./cmd/gen"}},
	}
	first, err := BuildGoEngineeringGraph(input)
	if err != nil {
		t.Fatal(err)
	}
	second, err := BuildGoEngineeringGraph(input)
	if err != nil {
		t.Fatal(err)
	}
	if first.Digest != second.Digest || first.Coverage != "PARTIAL" {
		t.Fatalf("graph was not deterministic/partial: %s %s %s", first.Digest, second.Digest, first.Coverage)
	}
	if first.Digest != "3bb6de3c6937904f337a9af98521d6cfaad6245895ebc0703621b47c3b915980" {
		t.Fatalf("legacy graph fixture digest changed: %s", first.Digest)
	}
	if err := ValidateGoEngineeringGraph(first); err != nil {
		t.Fatal(err)
	}
	symbols, err := QueryGoSymbols(first, GoSymbolQuery{NamePrefix: "New", Kind: "function_declaration", Limit: 10})
	if err != nil || len(symbols) != 1 || symbols[0].Path != "src/api.go" {
		t.Fatalf("symbol query: %#v err=%v", symbols, err)
	}
	imports, err := QueryGoImports(first, GoImportQuery{ImportPath: "fmt", Limit: 10})
	if err != nil || len(imports) != 2 {
		t.Fatalf("import query: %#v err=%v", imports, err)
	}
	limitedImports, err := QueryGoImports(first, GoImportQuery{ImportPath: "fmt", Limit: 1})
	if err != nil || len(limitedImports) != 1 || nodeLabel(first.Nodes, limitedImports[0].To) != "fmt" {
		t.Fatalf("bounded import query: %#v err=%v", limitedImports, err)
	}
	calls, err := QueryGoCalls(first, GoCallQuery{SpellingPrefix: "New", Limit: 10})
	if err != nil || len(calls) != 1 || calls[0].Resolution != "UNRESOLVED" {
		t.Fatalf("call query incorrectly resolved syntax: %#v err=%v", calls, err)
	}
	limitedCalls, err := QueryGoCalls(first, GoCallQuery{Path: "consumer/use.go", Limit: 1})
	if err != nil || len(limitedCalls) != 1 || limitedCalls[0].Resolution != "UNRESOLVED" {
		t.Fatalf("bounded call query: %#v err=%v", limitedCalls, err)
	}
	if !hasGoEdge(first.Edges, "TESTS", "src/api_test.go", "") || !hasGoEdge(first.Edges, "GENERATED_BY", "src/generated.go", "EXPLICIT_SOURCE_BOUND") || !hasGoEdge(first.Edges, "CALL_NAME_CANDIDATE", "src/api.go", "UNRESOLVED") {
		t.Fatal("explicit test/generator/advisory call relations missing")
	}
	impact, err := QueryGoImpact(first, GoImpactQuery{Paths: []string{"src/api.go"}, MaxDepth: 3, Limit: 20})
	if err != nil {
		t.Fatal(err)
	}
	if impact.Coverage != "PARTIAL" || !containsPath(impact.Paths, "src/generated.go") || !containsPath(impact.Paths, "src/api_test.go") || !containsPath(impact.Paths, "src/api_internal_test.go") || !containsPath(impact.Paths, "consumer/use.go") {
		t.Fatalf("unexpected impact result: %#v", impact)
	}
}

func TestApplyGoEngineeringOverlayDeletionDoesNotMutateBaseOrLeaveStaleEdges(t *testing.T) {
	producer := strings.Repeat("c", 64)
	oldSource := "package p\nfunc Gone() {}\n"
	oldFile := graphInput("pkg/old.go", oldSource, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"}, []GoSymbol{{Name: "Gone", Kind: "function_declaration", Range: graphSpan(oldSource, "Gone", 0)}}, nil, nil, nil, producer)
	useSource := "package p\nfunc use() { Gone() }\n"
	useFile := graphInput("pkg/use.go", useSource, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"}, []GoSymbol{{Name: "use", Kind: "function_declaration", Range: graphSpan(useSource, "use", 0)}}, nil, []GoCall{{Spelling: "Gone", Resolution: "UNRESOLVED", Range: graphSpan(useSource, "Gone", strings.Index(useSource, "{")+1)}}, nil, producer)
	base, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), CandidateID: strings.Repeat("d", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{oldFile, useFile}})
	if err != nil {
		t.Fatal(err)
	}
	baseDigest := base.Digest
	updated, err := ApplyGoEngineeringOverlay(base, GoGraphOverlayInput{BaseDigest: base.Digest, CandidateID: strings.Repeat("e", 64), ProducerSHA256: producer, Deleted: []string{"pkg/old.go"}})
	if err != nil {
		t.Fatal(err)
	}
	if base.Digest != baseDigest || len(base.Files) != 2 || len(updated.Files) != 1 || updated.CandidateID == base.CandidateID || updated.SourceID != base.SourceID {
		t.Fatalf("overlay mutated/reused base identity: base=%#v updated=%#v", base, updated)
	}
	for _, node := range updated.Nodes {
		if node.Path == "pkg/old.go" || (node.Kind == "declaration" && node.Label == "Gone") {
			t.Fatalf("stale deleted-file node remains: %+v", node)
		}
	}
	for _, edge := range updated.Edges {
		if edge.Path == "pkg/old.go" || edge.To == graphSymbolNodeID("pkg/old.go", oldFile.Facts.Declarations[0]) {
			t.Fatalf("stale deleted-file edge remains: %+v", edge)
		}
	}
	if _, err := QueryGoImpact(updated, GoImpactQuery{Paths: []string{"pkg/old.go"}, MaxDepth: 2, Limit: 10}); err == nil {
		t.Fatal("impact query accepted absent deleted path")
	}
	callEdges, err := QueryGoCalls(updated, GoCallQuery{SpellingPrefix: "Gone", Limit: 10})
	if err != nil || len(callEdges) != 1 || callEdges[0].Resolution != "UNRESOLVED" {
		t.Fatalf("syntactic call must remain unresolved after declaration deletion: %#v err=%v", callEdges, err)
	}
}

func TestApplyGoEngineeringOverlayReplacesOnlyNamedCandidateFile(t *testing.T) {
	producer := strings.Repeat("8", 64)
	oldSource := "package p\nfunc Before() {}\n"
	oldFile := graphInput("pkg/a.go", oldSource, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"}, []GoSymbol{{Name: "Before", Kind: "function_declaration", Range: graphSpan(oldSource, "Before", 0)}}, nil, nil, nil, producer)
	otherSource := "package p\nfunc Stable() {}\n"
	otherFile := graphInput("pkg/b.go", otherSource, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"}, []GoSymbol{{Name: "Stable", Kind: "function_declaration", Range: graphSpan(otherSource, "Stable", 0)}}, nil, nil, nil, producer)
	base, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), CandidateID: strings.Repeat("9", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{oldFile, otherFile}})
	if err != nil {
		t.Fatal(err)
	}
	newSource := "package p\nfunc After() {}\n"
	newFile := graphInput("pkg/a.go", newSource, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"}, []GoSymbol{{Name: "After", Kind: "function_declaration", Range: graphSpan(newSource, "After", 0)}}, nil, nil, nil, producer)
	updated, err := ApplyGoEngineeringOverlay(base, GoGraphOverlayInput{BaseDigest: base.Digest, CandidateID: strings.Repeat("a", 64), ProducerSHA256: producer, Replacements: []GoGraphFileInput{newFile}})
	if err != nil {
		t.Fatal(err)
	}
	if base.CandidateID == updated.CandidateID || len(base.Files) != 2 || len(updated.Files) != 2 || base.Digest == updated.Digest {
		t.Fatalf("replacement did not produce a separate candidate graph: base=%+v updated=%+v", base, updated)
	}
	if !hasGoDeclaration(updated, "pkg/a.go", "After") || hasGoDeclaration(updated, "pkg/a.go", "Before") || !hasGoDeclaration(updated, "pkg/b.go", "Stable") {
		t.Fatal("replacement left stale facts or changed an unaffected file")
	}
	if !hasGoDeclaration(base, "pkg/a.go", "Before") || hasGoDeclaration(base, "pkg/a.go", "After") {
		t.Fatal("replacement mutated base graph")
	}
}

func TestBaseGoGraphUsesSourceIdentityAndCanBePromotedToCandidateOverlay(t *testing.T) {
	producer := strings.Repeat("7", 64)
	sourceID := strings.Repeat("6", 64)
	source := "package p\nfunc Base() {}\n"
	file := graphInput("pkg/base.go", source, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"}, []GoSymbol{{Name: "Base", Kind: "function_declaration", Range: graphSpan(source, "Base", 0)}}, nil, nil, nil, producer)
	base, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, ProducerSHA256: producer, Files: []GoGraphFileInput{file}})
	if err != nil {
		t.Fatal(err)
	}
	if base.CandidateID != "" || base.SourceID != sourceID {
		t.Fatalf("base graph conflates source and candidate identity: %+v", base)
	}
	newSource := "package p\nfunc Candidate() {}\n"
	newFile := graphInput("pkg/base.go", newSource, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"}, []GoSymbol{{Name: "Candidate", Kind: "function_declaration", Range: graphSpan(newSource, "Candidate", 0)}}, nil, nil, nil, producer)
	updated, err := ApplyGoEngineeringOverlay(base, GoGraphOverlayInput{BaseDigest: base.Digest, CandidateID: strings.Repeat("5", 64), ProducerSHA256: producer, Replacements: []GoGraphFileInput{newFile}})
	if err != nil {
		t.Fatal(err)
	}
	if updated.CandidateID == "" || updated.SourceID != sourceID {
		t.Fatalf("overlay did not preserve source and add candidate identity: %+v", updated)
	}
	if _, err := ApplyGoEngineeringOverlay(base, GoGraphOverlayInput{BaseDigest: base.Digest, SourceID: strings.Repeat("4", 64), CandidateID: strings.Repeat("3", 64), ProducerSHA256: producer, Replacements: []GoGraphFileInput{newFile}}); err == nil {
		t.Fatal("overlay source identity substitution accepted")
	}
}

func TestSourceLocalPackageIdentityIsStableAndNeverResolvesImports(t *testing.T) {
	sourceID := strings.Repeat("c", 64)
	producer := strings.Repeat("b", 64)
	firstBinding, err := SourceLocalGoPackageBinding(sourceID, "src/pkg/a.go", "pkg")
	if err != nil {
		t.Fatal(err)
	}
	secondBinding, err := SourceLocalGoPackageBinding(sourceID, "src/pkg/b.go", "pkg")
	if err != nil {
		t.Fatal(err)
	}
	internalTestBinding, err := SourceLocalGoPackageBinding(sourceID, "src/pkg/a_test.go", "pkg")
	if err != nil {
		t.Fatal(err)
	}
	externalTestBinding, err := SourceLocalGoPackageBinding(sourceID, "src/pkg/external_test.go", "pkg_test")
	if err != nil {
		t.Fatal(err)
	}
	otherDirectory, err := SourceLocalGoPackageBinding(sourceID, "src/other/c.go", "pkg")
	if err != nil {
		t.Fatal(err)
	}
	if firstBinding.PackageIdentity != secondBinding.PackageIdentity || firstBinding.PackageIdentity != internalTestBinding.PackageIdentity || firstBinding.PackageIdentity == otherDirectory.PackageIdentity || firstBinding.PackageIdentity == externalTestBinding.PackageIdentity || externalTestBinding.TestOfPackageIdentity != firstBinding.PackageIdentity {
		t.Fatal("source-local package identity is not stable by source and directory")
	}
	localASource := "package pkg\nfunc A() {}\n"
	localA := graphInput("src/pkg/a.go", localASource, firstBinding, []GoSymbol{{Name: "A", Kind: "function_declaration", Range: graphSpan(localASource, "A", 0)}}, nil, nil, nil, producer)
	localBSource := "package pkg\nfunc B() {}\n"
	localB := graphInput("src/pkg/b.go", localBSource, secondBinding, []GoSymbol{{Name: "B", Kind: "function_declaration", Range: graphSpan(localBSource, "B", 0)}}, nil, nil, nil, producer)
	testSource := "package pkg\nfunc TestA() {}\n"
	internalTest := graphInput("src/pkg/a_test.go", testSource, internalTestBinding, []GoSymbol{{Name: "TestA", Kind: "function_declaration", Test: true, Range: graphSpan(testSource, "TestA", 0)}}, nil, nil, nil, producer)
	externalTestSource := "package pkg_test\nfunc TestAExternal() {}\n"
	externalTest := graphInput("src/pkg/external_test.go", externalTestSource, externalTestBinding, []GoSymbol{{Name: "TestAExternal", Kind: "function_declaration", Test: true, Range: graphSpan(externalTestSource, "TestAExternal", 0)}}, nil, nil, nil, producer)
	consumerSource := "package use\nimport \"example.com/m/pkg\"\nfunc Use() {}\n"
	consumer := graphInput("cmd/use.go", consumerSource, GoPackageBinding{ImportPath: "example.com/m/cmd", ModulePath: "example.com/m"}, []GoSymbol{{Name: "Use", Kind: "function_declaration", Range: graphSpan(consumerSource, "Use", 0)}}, []GoImport{{Path: "example.com/m/pkg", Range: graphSpan(consumerSource, `"example.com/m/pkg"`, 0)}}, nil, nil, producer)
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, ProducerSHA256: producer, Files: []GoGraphFileInput{localA, localB, internalTest, externalTest, consumer}})
	if err != nil {
		t.Fatal(err)
	}
	localNodeID := graphPackageBindingNodeID(firstBinding)
	var localNode *GoGraphNode
	for i := range graph.Nodes {
		if graph.Nodes[i].ID == localNodeID {
			localNode = &graph.Nodes[i]
		}
	}
	if localNode == nil || localNode.Kind != "source_local_package" || localNode.Label != firstBinding.PackageIdentity {
		t.Fatalf("source-local package node missing or mislabeled: %+v", localNode)
	}
	if !hasGraphEdgeTarget(graph.Edges, "IN_PACKAGE", "src/pkg/a.go", localNodeID) || !hasGraphEdgeTarget(graph.Edges, "IN_PACKAGE", "src/pkg/b.go", localNodeID) || !hasGraphEdgeTarget(graph.Edges, "TESTS", "src/pkg/a_test.go", localNodeID) {
		t.Fatal("same-directory source files/test did not share source-local package relation")
	}
	externalNodeID := graphPackageBindingNodeID(externalTestBinding)
	if externalNodeID == localNodeID || !hasGraphEdgeTarget(graph.Edges, "TESTS", "src/pkg/external_test.go", localNodeID) || !hasGraphEdgeTarget(graph.Edges, "IN_PACKAGE", "src/pkg/external_test.go", externalNodeID) {
		t.Fatal("external test package did not retain separate package identity and explicit target")
	}
	imports, err := QueryGoImports(graph, GoImportQuery{ImportPath: "example.com/m/pkg", Limit: 10})
	if err != nil || len(imports) != 1 {
		t.Fatalf("explicit import query: %#v err=%v", imports, err)
	}
	for _, node := range graph.Nodes {
		if node.ID == imports[0].To && node.Kind != "import" {
			t.Fatalf("synthetic source-local identity was treated as import resolution: %+v", node)
		}
	}
	if _, err := SourceLocalGoPackageBinding("bad", "src/pkg/a.go", "pkg"); err == nil {
		t.Fatal("invalid source identity accepted")
	}
	if _, err := SourceLocalGoPackageBinding(sourceID, "../escape.go", "pkg"); err == nil {
		t.Fatal("escaping source path accepted")
	}
	wrongDirectory := localA
	wrongDirectory.Package.SourceDirectory = "src/other"
	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, ProducerSHA256: producer, Files: []GoGraphFileInput{wrongDirectory}}); err == nil {
		t.Fatal("source-local package directory substitution accepted")
	}
}

func TestGoEngineeringGraphRejectsAmbiguityBindingsAndBounds(t *testing.T) {
	producer := strings.Repeat("f", 64)
	source := "package p\nfunc Run() {}\nfunc Run() {}\nfunc caller() { Run() }\nfunc selector(x T) { x.Run() }\n"
	firstRun := graphSpan(source, "Run", 0)
	secondRun := graphSpan(source, "Run", firstRun.EndByte)
	callRun := graphSpan(source, "Run", secondRun.EndByte)
	selectorRun := graphSpan(source, "x.Run", strings.Index(source, "func selector"))
	input := graphInput("pkg/ambiguous.go", source, GoPackageBinding{ImportPath: "example.com/m/pkg", ModulePath: "example.com/m"},
		[]GoSymbol{{Name: "Run", Kind: "function_declaration", Range: firstRun}, {Name: "Run", Kind: "function_declaration", Range: secondRun}, {Name: "caller", Kind: "function_declaration", Range: graphSpan(source, "caller", 0)}, {Name: "selector", Kind: "function_declaration", Range: graphSpan(source, "selector", 0)}}, nil,
		[]GoCall{{Spelling: "Run", Resolution: "UNRESOLVED", Range: callRun}, {Spelling: "x.Run", Resolution: "UNRESOLVED", Range: selectorRun}}, nil, producer)
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), CandidateID: strings.Repeat("1", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{input}})
	if err != nil {
		t.Fatal(err)
	}
	for _, edge := range graph.Edges {
		if edge.Relation == "CALL_NAME_CANDIDATE" {
			t.Fatalf("ambiguous or selector call gained an advisory target: %+v", edge)
		}
		if edge.Relation == "CALLS_UNRESOLVED" && edge.Resolution != "UNRESOLVED" {
			t.Fatalf("call falsely resolved: %+v", edge)
		}
	}

	badSource := input
	badSource.Source = []byte("package p\n")
	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), CandidateID: strings.Repeat("2", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{badSource}}); err == nil {
		t.Fatal("source/fact mismatch accepted")
	}
	duplicate := input
	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), CandidateID: strings.Repeat("3", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{input, duplicate}}); err == nil {
		t.Fatal("duplicate file path accepted")
	}
	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), CandidateID: "BAD", ProducerSHA256: producer, Files: []GoGraphFileInput{input}}); err == nil {
		t.Fatal("malformed candidate binding accepted")
	}
	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: "BAD", CandidateID: strings.Repeat("2", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{input}}); err == nil {
		t.Fatal("malformed source binding accepted")
	}
	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("0", 64), CandidateID: strings.Repeat("4", 64), ProducerSHA256: strings.Repeat("0", 64), Files: []GoGraphFileInput{input}}); err == nil {
		t.Fatal("producer substitution accepted")
	}
	if _, err := ApplyGoEngineeringOverlay(graph, GoGraphOverlayInput{BaseDigest: strings.Repeat("0", 64), CandidateID: strings.Repeat("5", 64), ProducerSHA256: producer, Deleted: []string{"pkg/ambiguous.go"}}); err == nil {
		t.Fatal("stale overlay base accepted")
	}
	if _, err := ApplyGoEngineeringOverlay(graph, GoGraphOverlayInput{BaseDigest: graph.Digest, CandidateID: graph.CandidateID, ProducerSHA256: producer, Deleted: []string{"pkg/ambiguous.go"}}); err == nil {
		t.Fatal("overlay candidate identity reuse accepted")
	}
	if _, err := QueryGoSymbols(graph, GoSymbolQuery{NamePrefix: "", Limit: goEngineeringMaxQuery + 1}); err == nil {
		t.Fatal("unbounded query accepted")
	}
	tampered := graph
	tampered.Coverage = "COMPLETE"
	if err := ValidateGoEngineeringGraph(tampered); err == nil {
		t.Fatal("tampered graph content accepted")
	}
}

func TestQueryGoSymbolsKindFilterAtScale(t *testing.T) {
	graph := largeGoSymbolGraph(t, 1200)
	got, err := QueryGoSymbols(graph, GoSymbolQuery{Kind: "function_declaration", Limit: 37})
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 37 {
		t.Fatalf("bounded kind query returned %d declarations, want 37", len(got))
	}
	for _, node := range got {
		if node.Kind != "declaration" || !strings.HasPrefix(node.Label, "Symbol") {
			t.Fatalf("kind query returned an invalid declaration: %+v", node)
		}
	}
}

func BenchmarkQueryGoSymbolsKindLargeGraph(b *testing.B) {
	graph := largeGoSymbolGraph(b, 1200)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := QueryGoSymbols(graph, GoSymbolQuery{Kind: "function_declaration", Limit: 37}); err != nil {
			b.Fatal(err)
		}
	}
}

func largeGoSymbolGraph(t testing.TB, count int) GoEngineeringGraph {
	t.Helper()
	var source strings.Builder
	declarations := make([]GoSymbol, 0, count)
	source.WriteString("package scale\n")
	for i := 0; i < count; i++ {
		prefix := fmt.Sprintf("func Symbol%04d() {}\n", i)
		nameStart := source.Len() + len("func ")
		declarations = append(declarations, GoSymbol{Name: fmt.Sprintf("Symbol%04d", i), Kind: "function_declaration", Range: GoRange{StartByte: nameStart, EndByte: nameStart + len(fmt.Sprintf("Symbol%04d", i))}})
		source.WriteString(prefix)
	}
	producer := strings.Repeat("9", 64)
	file := graphInput("scale/symbols.go", source.String(), GoPackageBinding{ImportPath: "example.com/m/scale", ModulePath: "example.com/m"}, declarations, nil, nil, nil, producer)
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: strings.Repeat("8", 64), CandidateID: strings.Repeat("7", 64), ProducerSHA256: producer, Files: []GoGraphFileInput{file}})
	if err != nil {
		t.Fatal(err)
	}
	return graph
}

func hasGoEdge(edges []GoGraphEdge, relation, path, resolution string) bool {
	for _, edge := range edges {
		if edge.Relation == relation && edge.Path == path && edge.Resolution == resolution {
			return true
		}
	}
	return false
}

func hasGraphEdgeTarget(edges []GoGraphEdge, relation, path, target string) bool {
	for _, edge := range edges {
		if edge.Relation == relation && edge.Path == path && edge.To == target {
			return true
		}
	}
	return false
}

func containsPath(paths []string, want string) bool {
	for _, path := range paths {
		if path == want {
			return true
		}
	}
	return false
}

func hasGoDeclaration(graph GoEngineeringGraph, path, name string) bool {
	for _, node := range graph.Nodes {
		if node.Kind == "declaration" && node.Path == path && node.Label == name {
			return true
		}
	}
	return false
}

func TestBuildGoEngineeringGraphWithDeclaredModuleInventory(t *testing.T) {
	root := t.TempDir()
	files := map[string][]byte{
		"go.mod":          []byte("module example.com/root\n\ngo 1.27\n"),
		"api/a.go":        []byte("package api\nfunc A() {}\n"),
		"api/a_test.go":   []byte("package api_test\n"),
		"nested/go.mod":   []byte("module example.com/nested\n\ngo 1.27\n"),
		"nested/pkg/b.go": []byte("package pkg\nfunc B() {}\n"),
		"cmd/use.go":      []byte("package cmd\nimport (\n \"example.com/root/api\"\n \"example.com/nested/pkg\"\n)\nfunc Use() { api.A(); pkg.B() }\n"),
	}
	initGoCorpusGit(t, root, files)
	identity, err := repository.Discover(context.Background(), root, "module-graph")
	if err != nil {
		t.Fatal(err)
	}
	inventory, err := CollectGoModuleInventory(context.Background(), identity)
	if err != nil {
		t.Fatal(err)
	}
	if err := ValidateGoModuleInventory(inventory, identity); err != nil {
		t.Fatal(err)
	}
	producer := strings.Repeat("b", 64)
	sourceID, err := identity.ID()
	if err != nil {
		t.Fatal(err)
	}
	inputs := make([]GoGraphFileInput, 0, 4)
	for _, name := range []string{"api/a.go", "api/a_test.go", "nested/pkg/b.go", "cmd/use.go"} {
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if err != nil {
			t.Fatal(err)
		}
		packageName := "api"
		switch name {
		case "api/a_test.go":
			packageName = "api_test"
		case "nested/pkg/b.go":
			packageName = "pkg"
		case "cmd/use.go":
			packageName = "cmd"
		}
		binding, err := DeclaredGoPackageBinding(inventory, name, packageName)
		if err != nil {
			t.Fatal(err)
		}
		imports := []GoImport(nil)
		if name == "cmd/use.go" {
			text := string(content)
			imports = []GoImport{{Path: "example.com/root/api", Range: graphSpan(text, `"example.com/root/api"`, 0)}, {Path: "example.com/nested/pkg", Range: graphSpan(text, `"example.com/nested/pkg"`, 0)}}
		}
		inputs = append(inputs, graphInput(name, string(content), binding, nil, imports, nil, nil, producer))
	}
	for _, input := range inputs {
		if err := validateGoPackageBinding(input.Package, input.Facts.Path, sourceID, &inventory); err != nil {
			t.Fatalf("binding %s invalid: %+v: %v", input.Facts.Path, input.Package, err)
		}
	}
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, ProducerSHA256: producer, Files: inputs, ModuleInventory: &inventory})
	if err != nil {
		t.Fatal(err)
	}
	if err := ValidateGoEngineeringGraph(graph); err != nil {
		t.Fatal(err)
	}
	if graph.ModuleInventory == nil || graph.ModuleInventory.Digest != inventory.Digest || !hasGoEdge(graph.Edges, "DECLARED_OWNERSHIP", "api/a.go", "DECLARED_MODULE_V1") {
		t.Fatalf("declared inventory evidence is missing from graph: %+v", graph.ModuleInventory)
	}
	apiID := graphPackageNodeID("example.com/root/api")
	if !hasGraphEdgeTarget(graph.Edges, "IMPORTS", "cmd/use.go", apiID) {
		t.Fatal("unique declared package import did not map to observed package")
	}
	var apiTest GoGraphFile
	for _, file := range graph.Files {
		if file.Facts.Path == "api/a_test.go" {
			apiTest = file
		}
	}
	if apiTest.Package.PackageIdentity == "" || graphPackageBindingNodeID(apiTest.Package) == apiID || !hasGraphEdgeTarget(graph.Edges, "TESTS", "api/a_test.go", apiID) {
		t.Fatal("external test package did not retain a distinct declared identity")
	}
	replayedBytes, err := json.Marshal(graph)
	if err != nil {
		t.Fatal(err)
	}
	var replayed GoEngineeringGraph
	if err := json.Unmarshal(replayedBytes, &replayed); err != nil || ValidateGoEngineeringGraph(replayed) != nil {
		t.Fatalf("declared inventory graph did not survive pure replay: %v", err)
	}

	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, CandidateID: strings.Repeat("c", 64), ProducerSHA256: producer, Files: inputs, ModuleInventory: &inventory}); err == nil {
		t.Fatal("candidate graph accepted a base-only module inventory")
	}
	if _, err := ApplyGoEngineeringOverlay(graph, GoGraphOverlayInput{BaseDigest: graph.Digest, CandidateID: strings.Repeat("c", 64), ProducerSHA256: producer}); err == nil {
		t.Fatal("module-backed graph accepted a candidate overlay without manifest closure")
	}
	tampered := inventory
	tampered.Digest = strings.Repeat("f", 64)
	if _, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, ProducerSHA256: producer, Files: inputs, ModuleInventory: &tampered}); err == nil {
		t.Fatal("tampered module inventory was accepted")
	}
}

func TestDeclaredGoPackageBindingFallsBackForIncompleteNestedModule(t *testing.T) {
	root := t.TempDir()
	initGoCorpusGit(t, root, map[string][]byte{
		"go.mod":          []byte("module example.com/root\n"),
		"nested/go.mod":   []byte("module example.com/nested\n"),
		"nested/pkg/a.go": []byte("package pkg\n"),
	})
	identity, err := repository.Discover(context.Background(), root, "module-fallback")
	if err != nil {
		t.Fatal(err)
	}
	inventory, err := CollectGoModuleInventory(context.Background(), identity)
	if err != nil {
		t.Fatal(err)
	}
	duplicate := cloneGoModuleInventory(inventory)
	for i := range duplicate.Files {
		if duplicate.Files[i].Path == "nested/go.mod" {
			duplicate.Files[i].ModulePath = "example.com/root"
		}
	}
	if err := finalizeGoModuleInventory(&duplicate); err != nil {
		t.Fatal(err)
	}
	duplicateBinding, err := DeclaredGoPackageBinding(duplicate, "nested/pkg/a.go", "pkg")
	if err != nil {
		t.Fatal(err)
	}
	if duplicateBinding.IdentityKind != "source_local_v1" {
		t.Fatalf("duplicate declared module path was treated as uniquely import-resolvable: %+v", duplicateBinding)
	}
	for i := range inventory.Files {
		if inventory.Files[i].Path == "nested/go.mod" {
			inventory.Files[i].Status = "invalid"
			inventory.Files[i].ModulePath = ""
			inventory.Coverage = "partial"
		}
	}
	if err := finalizeGoModuleInventory(&inventory); err != nil {
		t.Fatal(err)
	}
	binding, err := DeclaredGoPackageBinding(inventory, "nested/pkg/a.go", "pkg")
	if err != nil {
		t.Fatal(err)
	}
	if binding.IdentityKind != "source_local_v1" || binding.ImportPath != "" {
		t.Fatalf("incomplete nested module incorrectly inherited ancestor ownership: %+v", binding)
	}
}
