package ri

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"harness.local/engorch/internal/repository"
)

func TestCollectCommittedGoCorpusParseCacheRequiresExplicitOptIn(t *testing.T) {
	cacheDir := filepath.Join(t.TempDir(), "cache")
	cases := []struct {
		name    string
		cache   string
		options GoCorpusOptions
		want    string
	}{
		{name: "legacy rejects cache", cache: cacheDir, want: "explicit EnableParseCache"},
		{name: "opt in requires directory", options: GoCorpusOptions{EnableParseCache: true}, want: "requires a cache directory"},
		{name: "opt in rejects relative directory", cache: "relative-cache", options: GoCorpusOptions{EnableParseCache: true}, want: "absolute, clean, and non-root"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := CollectCommittedGoCorpusWithOptions(context.Background(), repository.Identity{}, Client{}, tc.cache, "objective", tc.options)
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("unexpected cache admission result: err=%v want substring %q", err, tc.want)
			}
		})
	}
}

func TestCollectCommittedGoCorpusParseCacheWarmReuseAndSourceInvalidation(t *testing.T) {
	client := actualGoCorpusClient(t)
	root := t.TempDir()
	initGoCorpusGit(t, root, map[string][]byte{
		"pkg/a.go":         []byte("package pkg\nfunc A() int { return 1 }\n"),
		"pkg/b.go":         []byte("package pkg\nfunc B() int { return A() }\n"),
		"pkg/gen.go":       []byte("package pkg\n//go:generate go run ./internal/gen -file=generated.go\n"),
		"pkg/generated.go": []byte("// Code generated by fixture. DO NOT EDIT.\npackage pkg\nfunc Generated() {}\n"),
	})
	identity, err := repository.Discover(context.Background(), root, "go-corpus-cache")
	if err != nil {
		t.Fatal(err)
	}
	cacheDir := filepath.Join(t.TempDir(), "ri-cache")
	options := GoCorpusOptions{EnableParseCache: true}
	cold, err := CollectCommittedGoCorpusWithOptions(context.Background(), identity, client, cacheDir, "generated package A B", options)
	if err != nil {
		t.Fatal(err)
	}
	warm, err := CollectCommittedGoCorpusWithOptions(context.Background(), identity, client, cacheDir, "generated package A B", options)
	if err != nil {
		t.Fatal(err)
	}
	assertCorpusFactsCache(t, cold, 0, len(cold.GraphInputs))
	assertCorpusFactsCache(t, warm, len(warm.GraphInputs), 0)
	assertCorpusCacheEquivalent(t, cold, warm)
	if cacheBytes := goCorpusFactsCacheBytes(t, cacheDir); cacheBytes <= 0 {
		t.Fatalf("warm parse cache did not retain cache entries: %d bytes", cacheBytes)
	}

	writeCorpusFile(t, root, "pkg/a.go", []byte("package pkg\nfunc A() int { return 2 }\n"))
	runCorpusGit(t, root, "add", "pkg/a.go")
	runCorpusGit(t, root, "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", "commit", "-qm", "change one source")
	changedIdentity, err := repository.Discover(context.Background(), root, "go-corpus-cache")
	if err != nil {
		t.Fatal(err)
	}
	changed, err := CollectCommittedGoCorpusWithOptions(context.Background(), changedIdentity, client, cacheDir, "generated package A B", options)
	if err != nil {
		t.Fatal(err)
	}
	assertCorpusFactsCache(t, changed, len(changed.GraphInputs)-1, 1)
	if changed.Source.Commit == cold.Source.Commit {
		t.Fatal("source edit did not create a distinct committed corpus identity")
	}
	if graphDigest(t, changed) == graphDigest(t, cold) {
		t.Fatal("changed source reused the previous graph identity")
	}
}

func assertCorpusFactsCache(t *testing.T, corpus GoCommittedCorpus, wantHits, wantMisses int) {
	t.Helper()
	hits, misses := 0, 0
	for _, input := range corpus.GraphInputs {
		switch {
		case input.Facts.Cache == "hit" && input.Facts.ParseCount == 0:
			hits++
		case input.Facts.Cache == "miss" && input.Facts.ParseCount == 1:
			misses++
		default:
			t.Fatalf("unexpected facts cache metrics for %s: cache=%q parse_count=%d", input.Facts.Path, input.Facts.Cache, input.Facts.ParseCount)
		}
	}
	if hits != wantHits || misses != wantMisses || hits+misses != corpus.ReadFiles {
		t.Fatalf("unexpected facts cache counts: hits=%d misses=%d read=%d want=%d/%d", hits, misses, corpus.ReadFiles, wantHits, wantMisses)
	}
}

func assertCorpusCacheEquivalent(t *testing.T, left, right GoCommittedCorpus) {
	t.Helper()
	if !reflect.DeepEqual(left.Sources, right.Sources) || left.ReadFiles != right.ReadFiles || left.AttemptedFiles != right.AttemptedFiles || left.OmittedCount != right.OmittedCount || !reflect.DeepEqual(left.Omissions, right.Omissions) || graphDigest(t, left) != graphDigest(t, right) {
		t.Fatal("cold/warm parse cache changed the committed corpus or graph identity")
	}
	leftInputs := append([]GoGraphFileInput(nil), left.GraphInputs...)
	rightInputs := append([]GoGraphFileInput(nil), right.GraphInputs...)
	for index := range leftInputs {
		leftInputs[index].Facts.Cache = ""
		leftInputs[index].Facts.ParseCount = 0
		rightInputs[index].Facts.Cache = ""
		rightInputs[index].Facts.ParseCount = 0
	}
	if !reflect.DeepEqual(leftInputs, rightInputs) {
		t.Fatal("cold/warm parse cache changed facts beyond cache metrics")
	}
}

func graphDigest(t *testing.T, corpus GoCommittedCorpus) string {
	t.Helper()
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: corpus.Source.RepositoryID, ProducerSHA256: corpus.GraphInputs[0].Facts.ProducerSHA256, Files: corpus.GraphInputs, Generators: corpus.Generators, ModuleInventory: corpus.ModuleInventory})
	if err != nil {
		t.Fatal(err)
	}
	return graph.Digest
}

func goCorpusFactsCacheBytes(t *testing.T, root string) int64 {
	t.Helper()
	var total int64
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		total += info.Size()
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return total
}

func writeCorpusFile(t *testing.T, root, name string, content []byte) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(name))
	if err := os.WriteFile(full, content, 0600); err != nil {
		t.Fatal(err)
	}
}

func runCorpusGit(t *testing.T, root string, args ...string) {
	t.Helper()
	command := exec.Command("git", append([]string{"-C", root}, args...)...)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v: %s", args, err, output)
	}
}

func BenchmarkCollectCommittedGoCorpusParseCache(b *testing.B) {
	client := goCorpusBenchmarkClient(b)
	root := b.TempDir()
	fixture := makeGoCorpusBenchmarkFixture()
	initGoCorpusBenchmarkGit(b, root, fixture)
	identity, err := repository.Discover(context.Background(), root, "go-corpus-parse-cache-benchmark")
	if err != nil {
		b.Fatal(err)
	}
	cacheRoot := b.TempDir()
	options := GoCorpusOptions{EnableParseCache: true}
	objective := "generated wrappers and package helpers"
	collect := func(cacheDir string) GoCommittedCorpus {
		b.Helper()
		corpus, err := CollectCommittedGoCorpusWithOptions(context.Background(), identity, client, cacheDir, objective, options)
		if err != nil {
			b.Fatal(err)
		}
		if corpus.ReadFiles != goCorpusMaxFiles {
			b.Fatalf("benchmark corpus has %d files, want %d", corpus.ReadFiles, goCorpusMaxFiles)
		}
		return corpus
	}
	fixtureBytes := 0
	for _, file := range fixture {
		fixtureBytes += len(file)
	}
	b.ReportMetric(float64(fixtureBytes), "source_B")

	b.Run("cold", func(b *testing.B) {
		b.ReportAllocs()
		b.ReportMetric(float64(fixtureBytes), "source-B/op")
		b.StopTimer()
		b.ResetTimer()
		var hits, misses int
		var diskBytes int64
		for index := 0; index < b.N; index++ {
			cacheDir, err := os.MkdirTemp(cacheRoot, fmt.Sprintf("cold-%d-", index))
			if err != nil {
				b.Fatal(err)
			}
			b.StartTimer()
			corpus := collect(cacheDir)
			b.StopTimer()
			for _, input := range corpus.GraphInputs {
				if input.Facts.Cache == "hit" {
					hits++
				} else if input.Facts.Cache == "miss" {
					misses++
				}
			}
			diskBytes += benchmarkCacheBytes(b, cacheDir)
		}
		b.ReportMetric(float64(hits)/float64(b.N), "cache_hits/op")
		b.ReportMetric(float64(misses)/float64(b.N), "cache_misses/op")
		b.ReportMetric(float64(diskBytes)/float64(b.N), "cache_bytes/op")
	})

	b.Run("warm", func(b *testing.B) {
		b.StopTimer()
		cacheDir, err := os.MkdirTemp(cacheRoot, "warm-")
		if err != nil {
			b.Fatal(err)
		}
		prime := collect(cacheDir)
		if prime.ReadFiles != goCorpusMaxFiles {
			b.Fatal("warm cache prime returned incomplete corpus")
		}
		b.ReportAllocs()
		b.ReportMetric(float64(fixtureBytes), "source-B/op")
		// Priming and instrumentation are excluded from both measurements.
		b.ResetTimer()
		var hits, misses int
		for index := 0; index < b.N; index++ {
			b.StartTimer()
			corpus := collect(cacheDir)
			b.StopTimer()
			for _, input := range corpus.GraphInputs {
				if input.Facts.Cache == "hit" {
					hits++
				} else if input.Facts.Cache == "miss" {
					misses++
				}
			}
		}
		b.ReportMetric(float64(hits)/float64(b.N), "cache_hits/op")
		b.ReportMetric(float64(misses)/float64(b.N), "cache_misses/op")
		b.ReportMetric(float64(benchmarkCacheBytes(b, cacheDir)), "cache_bytes")
	})
}

func makeGoCorpusBenchmarkFixture() map[string][]byte {
	files := make(map[string][]byte, goCorpusMaxFiles)
	files["pkg/gen.go"] = []byte("package pkg\n//go:generate go run ./internal/gen -file=generated.go\nfunc Generate() {}\n")
	files["pkg/generated.go"] = []byte("// Code generated by fixture. DO NOT EDIT.\npackage pkg\nfunc Generated() {}\n")
	files["pkg/internal/gen/main.go"] = []byte("package main\nfunc main() {}\n")
	for index := 0; len(files) < goCorpusMaxFiles; index++ {
		name := fmt.Sprintf("pkg/file%02d.go", index)
		var content strings.Builder
		fmt.Fprintf(&content, "package pkg\n\n// File%02d models a bounded helper source file in the fixture corpus.\n", index)
		for function := 0; function < 24; function++ {
			fmt.Fprintf(&content, "func File%02dFunction%02d(value int) int { return value + %d }\n", index, function, function)
		}
		files[name] = []byte(content.String())
	}
	return files
}

func initGoCorpusBenchmarkGit(b *testing.B, root string, files map[string][]byte) {
	b.Helper()
	run := func(args ...string) {
		b.Helper()
		command := exec.Command("git", append([]string{"-C", root}, args...)...)
		if output, err := command.CombinedOutput(); err != nil {
			b.Fatalf("git %v: %v: %s", args, err, output)
		}
	}
	run("init", "-q")
	for name, content := range files {
		full := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(full), 0700); err != nil {
			b.Fatal(err)
		}
		if err := os.WriteFile(full, content, 0600); err != nil {
			b.Fatal(err)
		}
	}
	run("add", ".")
	run("-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "-c", "commit.gpgsign=false", "commit", "-qm", "benchmark Go corpus")
}

func goCorpusBenchmarkClient(b *testing.B) Client {
	b.Helper()
	executable := os.Getenv("ENGORCH_RI_BINARY")
	if executable == "" {
		b.Skip("set ENGORCH_RI_BINARY to the pinned Rust RI binary")
	}
	executable, err := filepath.Abs(executable)
	if err != nil {
		b.Fatal(err)
	}
	binary, err := os.ReadFile(executable)
	if err != nil {
		b.Fatal(err)
	}
	digest := sha256.Sum256(binary)
	return Client{Executable: executable, ExecutableHash: hex.EncodeToString(digest[:])}
}

func benchmarkCacheBytes(b *testing.B, root string) int64 {
	b.Helper()
	var total int64
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		total += info.Size()
		return nil
	})
	if err != nil {
		b.Fatal(err)
	}
	return total
}
