package ri

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"harness.local/engorch/internal/canonical"
	"harness.local/engorch/internal/repository"
	"harness.local/engorch/internal/taskcontext"
)

func TestGoContractGenerationFilesBindLiteralClosure(t *testing.T) {
	common, filesByPath := goContractGenerationFixture(t, true)
	metadata := *common.Generation
	full, err := CompileGoContractContext(common)
	if err != nil {
		t.Fatal(err)
	}
	subset := literalGenerationFiles(metadata)
	if len(subset) >= len(metadata.ContextFiles) {
		t.Fatalf("fixture did not retain an irrelevant sibling: subset=%d corpus=%d", len(subset), len(metadata.ContextFiles))
	}
	explicitInput := common
	explicitInput.GenerationFiles = subset
	explicit, err := CompileGoContractContext(explicitInput)
	if err != nil {
		t.Fatal(err)
	}
	if explicit.Digest != full.Digest || !sameContractExcerpts(explicit.Excerpts, full.Excerpts) || !sameContractOmissions(explicit.Omissions, full.Omissions) {
		t.Fatalf("literal source subset changed contract result: digest_equal=%t excerpts=%d/%d omissions=%d/%d", explicit.Digest == full.Digest, len(explicit.Excerpts), len(full.Excerpts), len(explicit.Omissions), len(full.Omissions))
	}
	if err := ValidateGoContractContext(explicit, explicitInput); err != nil {
		t.Fatalf("explicit literal subset did not validate: %v", err)
	}
	if _, err := CompileGoContractContext(GoContractContextInput{SourceID: common.SourceID, Graph: common.Graph, ModuleInventory: common.ModuleInventory, Objective: common.Objective, Files: common.Files, GenerationFiles: subset}); err == nil {
		t.Fatal("generation files without metadata accepted")
	}
	duplicate := append(append([]taskcontext.File(nil), subset...), subset[0])
	bad := common
	bad.GenerationFiles = duplicate
	if _, err := CompileGoContractContext(bad); err == nil {
		t.Fatal("duplicate generation source accepted")
	}
	forged := append([]taskcontext.File(nil), subset...)
	forged[0].Content = append([]byte(nil), forged[0].Content...)
	forged[0].Content = append(forged[0].Content, '\n')
	sum := sha256.Sum256(forged[0].Content)
	forged[0].Hash = hex.EncodeToString(sum[:])
	bad = common
	bad.GenerationFiles = forged
	if _, err := CompileGoContractContext(bad); err == nil {
		t.Fatal("self-rehashed generation source substitution accepted")
	}
	missing := subset[1:]
	bad = common
	bad.GenerationFiles = missing
	if _, err := CompileGoContractContext(bad); err == nil {
		t.Fatal("incomplete literal generation closure accepted")
	}
	extra := append(append([]taskcontext.File(nil), subset...), filesByPath["irrelevant.go"])
	bad = common
	bad.GenerationFiles = extra
	if _, err := CompileGoContractContext(bad); err == nil {
		t.Fatal("unbound generation sibling source accepted")
	}
}

func goContractGenerationFixture(t *testing.T, includeIrrelevant bool) (GoContractContextInput, map[string]taskcontext.File) {
	t.Helper()
	files := map[string]string{
		"go.mod":                             "module example.test/root\n\ngo 1.25\n",
		"generated.go":                       "// Code generated by gen. DO NOT EDIT.\npackage sample\ntype Generated struct{}\n",
		"owner.go":                           "package sample\n//go:generate bin/gen-wrapper -file=generated.go\nfunc Target() {}\n",
		"Makefile":                           "GOBIN = $(shell pwd)/bin\nGEN_WRAPPER = $(GOBIN)/gen-wrapper\n$(GEN_WRAPPER): $(wildcard ./internal/gen-wrapper/*)\n\tgo build -o $@ ./internal/gen-wrapper\n",
		"internal/gen-wrapper/main.go":       "package main\nimport _ \"embed\"\n//go:embed *.tmpl\nvar template string\nfunc main() {}\n",
		"internal/gen-wrapper/template.tmpl": "{{define \"generated\"}}\n",
	}
	if includeIrrelevant {
		files["irrelevant.go"] = "package sample\nfunc IrrelevantSibling() {}\n"
	}
	identity := goModuleFixture(t, files)
	metadata, err := DiscoverCommittedGoGenerators(context.Background(), identity, []string{"generated.go", "owner.go"})
	if err != nil {
		t.Fatal(err)
	}
	if includeIrrelevant {
		metadata = addIrrelevantGenerationSibling(t, identity, metadata, "irrelevant.go")
	}
	if err := ValidateGoGenerationMetadata(metadata); err != nil {
		t.Fatal("generation fixture metadata invalid")
	}
	inventory, err := CollectGoModuleInventory(context.Background(), identity)
	if err != nil {
		t.Fatal(err)
	}
	sourceID, err := identity.ID()
	if err != nil {
		t.Fatal(err)
	}
	byPath := make(map[string]taskcontext.File, len(metadata.ContextFiles))
	for _, file := range metadata.ContextFiles {
		byPath[file.Path] = file
	}
	owner, generated := byPath["owner.go"], byPath["generated.go"]
	if owner.Path == "" || generated.Path == "" {
		t.Fatal("required graph fixture files absent")
	}
	producer := strings.Repeat("c", 64)
	ownerBinding, err := DeclaredGoPackageBinding(inventory, "owner.go", "sample")
	if err != nil {
		t.Fatal(err)
	}
	generatedBinding, err := DeclaredGoPackageBinding(inventory, "generated.go", "sample")
	if err != nil {
		t.Fatal(err)
	}
	ownerIn := graphInput("owner.go", string(owner.Content), ownerBinding, []GoSymbol{{Name: "Target", Kind: "function_declaration", Range: graphSpan(string(owner.Content), "Target", 0)}}, nil, nil, []string{"//go:generate bin/gen-wrapper -file=generated.go"}, producer)
	generatedIn := graphInput("generated.go", string(generated.Content), generatedBinding, []GoSymbol{{Name: "Generated", Kind: "type_spec", Range: graphSpan(string(generated.Content), "Generated", 0)}}, nil, nil, []string{"// Code generated by gen. DO NOT EDIT."}, producer)
	graph, err := BuildGoEngineeringGraph(GoGraphSnapshotInput{SourceID: sourceID, ProducerSHA256: producer, Files: []GoGraphFileInput{ownerIn, generatedIn}, ModuleInventory: &inventory, Generators: []GoGeneratorBinding{{GeneratorPath: "owner.go", GeneratedPath: "generated.go", Directive: "//go:generate bin/gen-wrapper -file=generated.go"}}})
	if err != nil {
		t.Fatal(err)
	}
	return GoContractContextInput{SourceID: sourceID, Graph: graph, ModuleInventory: &inventory, Generation: &metadata, Objective: "Update Generated generator template", Files: []taskcontext.File{owner, generated}}, byPath
}

func addIrrelevantGenerationSibling(t *testing.T, identity repository.Identity, metadata GoGenerationMetadata, path string) GoGenerationMetadata {
	t.Helper()
	for _, source := range metadata.Sources {
		if source.Path == path {
			return metadata
		}
	}
	content, err := os.ReadFile(filepath.Join(identity.Root, filepath.FromSlash(path)))
	if err != nil {
		t.Fatal(err)
	}
	digest, err := repository.DigestSource(context.Background(), identity, path)
	if err != nil {
		t.Fatal(err)
	}
	metadata.Sources = append(metadata.Sources, digest)
	metadata.ContextFiles = append(metadata.ContextFiles, taskcontext.File{Path: path, Hash: digest.SHA256, Content: content})
	sort.Slice(metadata.Sources, func(i, j int) bool { return metadata.Sources[i].Path < metadata.Sources[j].Path })
	sort.Slice(metadata.ContextFiles, func(i, j int) bool { return metadata.ContextFiles[i].Path < metadata.ContextFiles[j].Path })
	body := metadata
	body.Digest = ""
	encoded, err := canonical.Bytes(body)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(encoded)
	metadata.Digest = hex.EncodeToString(sum[:])
	return metadata
}

func literalGenerationFiles(metadata GoGenerationMetadata) []taskcontext.File {
	needed := map[string]bool{}
	for _, binding := range metadata.Bindings {
		needed[binding.GeneratorPath] = true
		needed[binding.GeneratedPath] = true
		for _, source := range binding.ToolSources {
			needed[source.Path] = true
		}
	}
	result := make([]taskcontext.File, 0, len(needed))
	for _, file := range metadata.ContextFiles {
		if needed[file.Path] {
			result = append(result, file)
		}
	}
	return result
}

func sameContractExcerpts(left, right []taskcontext.SelectedFile) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i] != right[i] {
			return false
		}
	}
	return true
}

func sameContractOmissions(left, right []taskcontext.Omission) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i] != right[i] {
			return false
		}
	}
	return true
}
