package ri

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"testing"
)

func TestActualRustGoFactsCRLFComments(t *testing.T) {
	executable := os.Getenv("ENGORCH_RI_BINARY")
	if executable == "" {
		t.Skip("set ENGORCH_RI_BINARY to built Rust RI")
	}
	bytes, err := os.ReadFile(executable)
	if err != nil {
		t.Fatal(err)
	}
	hash := sha256.Sum256(bytes)
	client := Client{Executable: executable, ExecutableHash: hex.EncodeToString(hash[:])}
	source := []byte("//go:generate echo nothing\r\n// Code generated by fixture. DO NOT EDIT.\r\npackage p\r\nimport `fmt`\r\nfunc F(){fmt.Println()}\r\n")
	facts, err := client.GoFileFacts(context.Background(), "crlf.go", source, "")
	if err != nil {
		t.Fatal(err)
	}
	if len(facts.GeneratedMarkers) != 2 || len(facts.Declarations) != 1 || len(facts.Calls) != 1 {
		t.Fatalf("CRLF facts omitted: %+v", facts)
	}
	cache := t.TempDir()
	cold, err := client.GoFileFacts(context.Background(), "crlf.go", source, cache)
	if err != nil {
		t.Fatal(err)
	}
	warm, err := client.GoFileFacts(context.Background(), "crlf.go", source, cache)
	if err != nil || warm.ParseCount != 0 || warm.BodySHA256 != cold.BodySHA256 {
		t.Fatalf("CRLF cache not reusable: %v", err)
	}
}
