package ri

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"reflect"
	"strings"
	"testing"

	"harness.local/engorch/internal/canonical"
	"harness.local/engorch/internal/repository"
	"harness.local/engorch/internal/taskcontext"
)

func TestDiscoverCommittedGoGeneratorsFindsSiblingOwnersAndExactEmbeddedToolSources(t *testing.T) {
	root := t.TempDir()
	files := map[string][]byte{
		"bool.go":                           []byte("// @generated Code generated by gen-wrapper. DO NOT EDIT.\npackage sample\ntype Bool struct{}\n"),
		"int64.go":                          []byte("// Code generated by gen-int. DO NOT EDIT.\npackage sample\ntype Int64 struct{}\n"),
		"bool_ext.go":                       []byte("package sample\n//go:generate bin/gen-wrapper -name=Bool -file=bool.go\nfunc (b *Bool) Toggle() {}\n"),
		"gen.go":                            []byte("package sample\n//go:generate bin/gen-int -name=Int64 -file=int64.go\n"),
		"Makefile":                          []byte("GOBIN = $(shell pwd)/bin\nGEN_WRAPPER = $(GOBIN)/gen-wrapper\nGEN_INT = $(GOBIN)/gen-int\n$(GEN_WRAPPER): $(wildcard ./internal/gen-wrapper/*)\n\tgo build -o $@ ./internal/gen-wrapper\n$(GEN_INT): $(wildcard ./internal/gen-int/*)\n\tgo build -o $@ ./internal/gen-int\n"),
		"internal/gen-wrapper/main.go":      []byte("package main\nimport _ \"embed\"\n//go:embed *.tmpl\nvar template string\nfunc main() {}\n"),
		"internal/gen-wrapper/wrapper.tmpl": []byte("{{define \"type\"}}type Bool struct{}{{end}}\n"),
		"internal/gen-int/main.go":          []byte("package main\nimport _ \"embed\"\n//go:embed *.tmpl\nvar template string\nfunc main() {}\n"),
		"internal/gen-int/wrapper.tmpl":     []byte(strings.Repeat("template marker\n", 600)),
	}
	initGoCorpusGit(t, root, files)
	identity, err := repository.Discover(context.Background(), root, "generation-fixture")
	if err != nil {
		t.Fatal(err)
	}
	first, err := DiscoverCommittedGoGenerators(context.Background(), identity, []string{"bool.go", "int64.go"})
	if err != nil {
		t.Fatal(err)
	}
	second, err := DiscoverCommittedGoGenerators(context.Background(), identity, []string{"int64.go", "bool.go"})
	if err != nil {
		t.Fatal(err)
	}
	if first.Digest != second.Digest || first.SeedDigest != second.SeedDigest {
		t.Fatalf("seed ordering changed deterministic metadata: %s/%s vs %s/%s", first.Digest, first.SeedDigest, second.Digest, second.SeedDigest)
	}
	if first.Coverage != "PARTIAL" || len(first.Bindings) != 2 {
		t.Fatalf("bounded sibling discovery did not retain both generator owners: coverage=%q bindings=%+v omissions=%+v", first.Coverage, first.Bindings, first.Omissions)
	}
	byOutput := map[string]GoGenerationBinding{}
	for _, binding := range first.Bindings {
		byOutput[binding.GeneratedPath] = binding
	}
	for output, owner := range map[string]string{"bool.go": "bool_ext.go", "int64.go": "gen.go"} {
		binding, ok := byOutput[output]
		if !ok || binding.GeneratorPath != owner || binding.OutputSource.Path != output || binding.DirectiveSource.Path != owner || !binding.ToolProvenanceComplete {
			t.Fatalf("generator binding for %s is incomplete: %+v", output, binding)
		}
		if binding.DirectiveRange.StartByte < 0 || binding.DirectiveRange.EndByte <= binding.DirectiveRange.StartByte || !strings.HasPrefix(binding.Directive, "//go:generate ") {
			t.Fatalf("directive source range is invalid: %+v", binding)
		}
		roles := map[string]string{}
		for _, ref := range binding.ToolSources {
			roles[ref.Path] = ref.Role
			if ref.Source.Path != ref.Path || ref.Source.RepositoryID != first.SourceID || ref.Source.Commit != identity.Commit || ref.Source.SHA256 == "" {
				t.Fatalf("tool source is not committed-source-bound: %+v", ref)
			}
		}
		if roles["Makefile"] != "build_definition" || roles["internal/gen-wrapper/wrapper.tmpl"] != "generator_template" && output == "bool.go" || roles["internal/gen-int/wrapper.tmpl"] != "generator_template" && output == "int64.go" {
			t.Fatalf("expected exact Makefile/embed template provenance for %s: %v", output, roles)
		}
	}
	if !contextFilePresent(first.ContextFiles, "internal/gen-wrapper/wrapper.tmpl") || !contextFilePresent(first.ContextFiles, "internal/gen-int/wrapper.tmpl") {
		t.Fatal("supporting embedded template content was not retained for bounded planner context")
	}
	if err := ValidateGoGenerationMetadata(first); err != nil {
		t.Fatalf("valid committed generation metadata did not validate: %v", err)
	}
	encoded, err := json.Marshal(first)
	if err != nil {
		t.Fatal(err)
	}
	var replay GoGenerationMetadata
	if err := json.Unmarshal(encoded, &replay); err != nil {
		t.Fatal(err)
	}
	if replay.ContextFiles != nil {
		t.Fatal("in-memory committed source bytes leaked into persisted metadata")
	}
	if err := ValidateGoGenerationMetadata(replay); err != nil {
		t.Fatalf("replayed metadata without transient bytes did not validate: %v", err)
	}
	overBudget := replay
	overBudget.Sources = append([]repository.SourceDigest(nil), replay.Sources...)
	for index := range overBudget.Sources {
		overBudget.Sources[index].Bytes = goGenerationMaxFileBytes
	}
	if err := ValidateGoGenerationMetadata(overBudget); err == nil || !strings.Contains(err.Error(), "aggregate byte limit") {
		t.Fatalf("metadata source byte aggregate was not bounded: %v", err)
	}
	contextResult, err := CompileGoGenerationContext(first, "Update the generated Bool and Int64 implementations and their generator templates.")
	if err != nil {
		t.Fatalf("compile bounded generation context: %v", err)
	}
	if contextResult.Coverage != "PARTIAL" || contextResult.SelectedBytes > goGenerationContextLimit || len(contextResult.Selected) == 0 {
		t.Fatalf("generation context exceeded its bound or claimed complete coverage: %+v", contextResult)
	}
	for _, item := range contextResult.Selected {
		if item.Start != 0 || item.End != int64(len(item.Content)) || item.ExcerptHash != item.Hash {
			t.Fatalf("generation context exposed a partial source that replay cannot independently authenticate: %+v", item)
		}
	}
	oversizedTemplateOmitted := false
	for _, omission := range contextResult.Omissions {
		if omission.Path == "internal/gen-int/wrapper.tmpl" && omission.Reason == "generation_context_complete_file_over_budget" {
			oversizedTemplateOmitted = true
		}
	}
	if !oversizedTemplateOmitted {
		t.Fatal("oversized complete template was not honestly omitted from the 8 KiB context")
	}
	if err := ValidateGoGenerationContext(contextResult, first); err != nil {
		t.Fatalf("compiled generation context did not validate: %v", err)
	}
	contextReplayJSON, err := json.Marshal(contextResult)
	if err != nil {
		t.Fatal(err)
	}
	var contextReplay GoGenerationContext
	if err := json.Unmarshal(contextReplayJSON, &contextReplay); err != nil {
		t.Fatal(err)
	}
	if contextReplay.ContextFiles != nil {
		t.Fatal("transient selected source bytes leaked into persisted context")
	}
	if err := ValidateGoGenerationContext(contextReplay, replay); err != nil {
		t.Fatalf("persisted generation context did not validate against replay metadata: %v", err)
	}
	forged := contextReplay
	forged.Selected = append([]taskcontext.SelectedFile(nil), contextReplay.Selected...)
	content := []byte(forged.Selected[0].Content)
	content[0] ^= 1
	forged.Selected[0].Content = string(content)
	forged.Selected[0].ExcerptHash = sha256Hex(content)
	forged.Digest = ""
	forged.Digest, err = canonical.Hash(goGenerationContextSchema, forged)
	if err != nil {
		t.Fatal(err)
	}
	if err := ValidateGoGenerationContext(forged, replay); err == nil {
		t.Fatal("self-rehashed forged partial/full content passed persisted source-hash validation")
	}
	contextReplay = GoGenerationContext{}
	if err := json.Unmarshal(contextReplayJSON, &contextReplay); err != nil {
		t.Fatal(err)
	}
	contextReplay.Selected[0].Reason = "generation_output"
	contextReplay.Digest = ""
	contextReplay.Digest, err = canonical.Hash(goGenerationContextSchema, contextReplay)
	if err != nil {
		t.Fatal(err)
	}
	if err := ValidateGoGenerationContext(contextReplay, replay); err == nil {
		t.Fatal("relabelled generation context source passed validation after digest recomputation")
	}
	for _, contextFile := range first.ContextFiles {
		if contextFile.Hash == "" || len(contextFile.Content) == 0 {
			t.Fatalf("context source lacks committed hash or bytes: %+v", contextFile)
		}
	}
}

func TestDiscoverCommittedGoGeneratorsRejectsShellTraversalDuplicateAndUnmarkedOutput(t *testing.T) {
	root := t.TempDir()
	files := map[string][]byte{
		"out.go": []byte("package p\n"),
		"owner.go": []byte("package p\n" +
			"//go:generate bin/g -file=../escape.go\n" +
			"//go:generate bin/g -file=out.go -file=out.go\n" +
			"//go:generate $GEN -file=out.go\n" +
			"//go:generate bin/g -file=out.go\n"),
	}
	initGoCorpusGit(t, root, files)
	identity, err := repository.Discover(context.Background(), root, "generation-invalid-fixture")
	if err != nil {
		t.Fatal(err)
	}
	result, err := DiscoverCommittedGoGenerators(context.Background(), identity, []string{"out.go"})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Bindings) != 0 || result.OmittedCount < 4 || result.Coverage != "PARTIAL" {
		t.Fatalf("unsafe or unmarked generation relation was accepted: %+v", result)
	}
	if _, _, err := parseLiteralGoGenerate("owner.go", "//go:generate bin/g -file=../escape.go"); err == nil {
		t.Fatal("path traversal output was accepted")
	}
	if _, _, err := parseLiteralGoGenerate("owner.go", "//go:generate bin/g -file=out.go -file=out.go"); err == nil {
		t.Fatal("duplicate output flag was accepted")
	}
	if _, _, err := parseLiteralGoGenerate("owner.go", "//go:generate $GEN -file=out.go"); err == nil {
		t.Fatal("shell-variable command was accepted")
	}
}

func TestGoGenerationSiblingSearchPrioritizesOwnersAndReportsBoundedOmission(t *testing.T) {
	seeds := map[string]bool{"int64.go": true, "uint64.go": true}
	paths := []repository.SourceEntry{
		{Path: "zz_last.go", Kind: "file"},
		{Path: "uint64.go", Kind: "file"},
		{Path: "bool_ext.go", Kind: "file"},
		{Path: "gen.go", Kind: "file"},
		{Path: "int64.go", Kind: "file"},
	}
	ordered := orderGoGenerationCandidates(paths, seeds)
	got := []string{ordered[0].Path, ordered[1].Path, ordered[2].Path, ordered[3].Path}
	want := []string{"int64.go", "uint64.go", "gen.go", "bool_ext.go"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("generator owner sibling priority changed: got %v want %v", got, want)
	}
	if goGenerationCandidateGroup("pkg/other.go", false) != 3 {
		t.Fatal("ordinary siblings must remain in the final deterministic search tier")
	}
}

func TestGoGenerationDirectiveRequiresScannerRecognizedLineStart(t *testing.T) {
	source := []byte("package p\n" +
		"func inline() { //go:generate bin/gen -file=out.go\n}\n" +
		"func indented() {\n    //go:generate bin/gen -file=out.go\n}\n" +
		"//go:generate bin/gen -file=out.go\n")
	directives, ok := parseGoGenerationDirectives("owner.go", source)
	if !ok {
		t.Fatal("valid source with non-directive comments did not parse")
	}
	if len(directives) != 1 || directives[0].Text != "//go:generate bin/gen -file=out.go" {
		t.Fatalf("inline or indented comment was treated as a generator directive: %+v", directives)
	}
}

func TestGoGenerationToolProvenanceBindsLiteralCommandPathNotBasename(t *testing.T) {
	makefile := []byte("export GOBIN ?= $(shell pwd)/bin\n" +
		"GEN_WRAPPER = $(GOBIN)/gen-wrapper\n" +
		"$(GEN_WRAPPER): $(wildcard ./internal/gen-wrapper/*)\n")
	makefiles := map[string][]byte{"Makefile": makefile}
	if match := matchGoGenerationToolDetails("bin/gen-wrapper", "bool_ext.go", makefiles); !match.complete || match.directory != "internal/gen-wrapper" {
		t.Fatalf("exact configured command did not match Makefile tool source: %+v", match)
	}
	if match := matchGoGenerationToolDetails("other/bin/gen-wrapper", "bool_ext.go", makefiles); match.complete {
		t.Fatalf("same basename with a different path incorrectly inherited tool provenance: %+v", match)
	}
	if match := matchGoGenerationToolDetails("bin/gen-wrapper", "pkg/bool_ext.go", makefiles); match.complete {
		t.Fatalf("nested owner command resolved against unrelated root GOBIN: %+v", match)
	}
}

func TestGoGenerationCopySkipsOversizedBlobWithoutRetainingPrefix(t *testing.T) {
	root := t.TempDir()
	large := []byte("package large\n//" + strings.Repeat("x", goGenerationMaxFileBytes))
	initGoCorpusGit(t, root, map[string][]byte{"large.go": large})
	identity, err := repository.Discover(context.Background(), root, "generation-size-fixture")
	if err != nil {
		t.Fatal(err)
	}
	entries := []repository.SourceEntry{}
	if err := repository.VisitSource(context.Background(), identity, func(entry repository.SourceEntry) error {
		entries = append(entries, entry)
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	reads, retained, omitted, err := copyGoGenerationSources(context.Background(), identity, entries, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(reads) != 0 || retained != 0 || omitted["large.go"] != "file_byte_limit" {
		t.Fatalf("oversized generator source was partially retained: reads=%d bytes=%d omitted=%v", len(reads), retained, omitted)
	}
}

func contextFilePresent(files []taskcontext.File, name string) bool {
	for _, file := range files {
		if file.Path == name {
			return true
		}
	}
	return false
}

func sha256Hex(content []byte) string {
	digest := sha256.Sum256(content)
	return hex.EncodeToString(digest[:])
}
